- name: ソースコードをGitHubから持ってくる
  git:
    repo:           https://github.com/zimbatm/direnv.git
    dest:           ~/dev/_others/direnv
    accept_hostkey: yes

- name: インストールする
  shell: cd ~/dev/_others/direnv; make install
